FROM java:8

RUN set -u \
 && apt-get update || : \
 && apt-get install -y --no-install-recommends rsync

RUN set -u \
 && mkdir /mvn \
 && cd /mvn \
 && wget https://www-us.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz \
 && tar xf apache-maven-3.6.1-bin.tar.gz \
 && ln -sf /mvn/apache-maven-3.6.1/bin/mvn /usr/local/bin/mvn

RUN set -u \
 && wget -O /usr/local/bin/docker_pid1 https://github.com/win-t/docker_pid1/releases/download/v3.2.0/docker_pid1 \
 && chmod 755 /usr/local/bin/docker_pid1

ENTRYPOINT ["docker_pid1"]
